### PR TITLE
Add bufferEntireResponse to request payload

### PR DESCRIPTION
**Pull request by adnauseum**
Depends on: https://github.com/VEuPathDB/WDKClient/pull/273/files#diff-681e5c1bd8a1dec438872ce300d050cf47a2dde3fd45b5d53b548b0fed100979R362 which will add the `bufferEntireResponse` type to the `StandardReportConfig` type.

This PR partially resolves: https://github.com/VEuPathDB/WDKClient/issues/262 along in addition to https://github.com/VEuPathDB/WDKClient/pull/273

### CODE REVIEW

**Review by dmfalke — APPROVED** [review]
This looks good. I think you accidentally committed your `.vscode` settings :smile:

**Comment by dmfalke** [comment]
Don't forget to version!

```
yarn version --patch
```

**Comment by adnauseum** [comment]
> This looks good. I think you accidentally committed your `.vscode` settings 😄

Lol yep, that's what prompted my search for a global `.gitignore` 😆 . I've removed it and have updated the repo's `.gitignore` in: https://github.com/VEuPathDB/web-app-preferred-organisms/pull/10/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R17

**Comment by adnauseum** [comment]
> 1146e4c

Danke! 🙇 Version bump: https://github.com/VEuPathDB/web-app-preferred-organisms/pull/10/commits/1146e4c9b780fd1e2092189322c111964078f064

**Pull request merged**
